<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-PO9H1NL" name="com.facebook.testcases.VerifyValidLogin" tests="5" failures="0" timestamp="06 Jul 2017 02:35:14 GMT" time="0.034" errors="1">
  <testcase name="checking" time="0.000" classname="com.facebook.testcases.VerifyValidLogin">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.facebook.testcases.utility.captureScreenShot(utility.java:15)
	at com.facebook.testcases.VerifyValidLogin.checking(VerifyValidLogin.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:723)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- checking -->
  <testcase name="checkValidUser2" time="0.000" classname="com.facebook.testcases.VerifyValidLogin">
    <skipped/>
  </testcase> <!-- checkValidUser2 -->
  <testcase name="checkValidUser" time="0.034" classname="com.facebook.testcases.VerifyValidLogin"/>
  <testcase name="checkValidUser1" time="0.000" classname="com.facebook.testcases.VerifyValidLogin">
    <skipped/>
  </testcase> <!-- checkValidUser1 -->
  <testcase name="checkValidUser3" time="0.000" classname="com.facebook.testcases.VerifyValidLogin">
    <skipped/>
  </testcase> <!-- checkValidUser3 -->
</testsuite> <!-- com.facebook.testcases.VerifyValidLogin -->
